name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
          config: baseUrl=http://localhost:8080/
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos  
    env:
      # pass the Dashboard record key as an environment variable
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # Recommended: pass the GitHub token lets this action correctly
      # determine the unique run id necessary to re-run the checks
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
